### PR TITLE
NN api, remove rank, mii data, archive to index.html

### PR DESCRIPTION
**Pull request by Gauley123**
stop using nnidlt and use nintendo network api

rank is not actually used in the API afaik, so i removed it but you can calculate it with:
1800000000 - pid

put the actual mii data in db.
add archive to index.html

### CODE REVIEW

**Comment by TermOfficial** [comment]
BOOOOOOO

**Comment by Rix565** [comment]
Great so far! Can you re-add rank (might be useful for someone) and remove the archive bar in index.html please? (You can put an <a> tag to link to the archive page on index.html)

**Comment by Rix565** [comment]
And make mii b64 again, it wont work great with the django admin panel else (i plan on making a download .mii file button)

**Comment by Gauley123** [comment]
Ok done

**Comment by Rix565** [comment]
Neat!

**Pull request merged**
